### ISSUE TITLE
Refactor and Modernize

### ISSUE THREAD

**Issue by the-pat** [the-pat/spooky#7]
After the other issues are complete, refactor and modernize the code base.

This issue is blocked by the following issues:

- [x] https://github.com/the-pat/spooky/issues/2
- [x] https://github.com/the-pat/spooky/issues/3
- [x] https://github.com/the-pat/spooky/issues/4
- [x] https://github.com/the-pat/spooky/issues/5

**Comment by ayushpareek1947** [comment]
What's the problem?

**Comment by the-pat** [comment]
@ayushpareek1947, there's not really a problem. But there are areas that can use updating:

- `var` -> `const` and `let`
- `"string" + "concatenation"` -> ``` `string ${"concatenation"}` ```
- the `urls` variable can be refactored out of the function into the module

@jakehamtexas did a great job at writing modern code in his PR, but I want this port to remain as close to [cornify](https://github.com/Cornify/Cornify/) until the other issues are completed. I'll update this issue description with the blocking issues.

**Comment by ayushpareek1947** [comment]
ohh yeah thanks

**Comment by jossiey** [comment]
Is anyone doing this issue? I'd like to give a try.

**Comment by jossiey** [comment]
Hi, is index.js missing?

**Comment by the-pat** [comment]
@jossiey, it is yours if you want it!

The `index.js` file was renamed to `spooky.js`.

**Comment by the-pat** [comment]
@jossiey, if interested, a previous PR was made that did a good job of refactoring the original code. You can check it out here for inspiration: https://github.com/the-pat/spooky/pull/1

**Comment by jossiey** [comment]
@the-pat  Thank you. I will start to refactor the code.

**Comment by jossiey** [comment]
@the-pat in package.json, the main file is still named "index.js", I think we need to modify it. It's confused.

**Comment by the-pat** [comment]
I see what you're talking about now.

Since this code is intended to run on browsers, rather than on servers, it doesn't needed the `package.json`. But if you would like to update the `package.json`, please look at the documentation for [`main` and `browser`](https://docs.npmjs.com/files/package.json#browser).

If you're wanting to play with the code locally (make sure it still runs as expected after the refactor), load the `index.html` file in your browser (I've been using the [Live Server extension](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) for VSCode).
